### ISSUE TITLE
linkid.be is no more available, end up in HTTP 503

### ISSUE THREAD

**Issue by dariusjb** [link-nv/logback-s3-rolling-policy#11]
Hi,

I wanted to rely on your appender, but the repository maven on which you publicly distribute your release is no more available.

Do you think you can publish it somewhere else? Or should I start from your source and build it in a local maven repository?

Regards

**Comment by wvdhaute** [comment]
Hello,

That repository is down forever, the company under which the repository was hosted, is no longer.
Solution for now is to build it yourself and install it in your local repo or on your internal company repo.
Apologies for the inconvenience.

Kind regards,
Wim
