### ISSUE TITLE
doesnt compile with new logback

### ISSUE THREAD

**Issue by jcocoder** [link-nv/logback-s3-rolling-policy#12]
Hi 
I got an compilation error :  `S3TimeBasedRollingPolicy.java:158: error: cannot find symbol
[ERROR]         if (future != null) {
[ERROR]             ^
[ERROR]
[ERROR] could not parse error message:   symbol:   variable future
[ERROR]   location: class S3TimeBasedRollingPolicy<E>`

**Comment by dhouthoo** [comment]
Master builds perfectly with an empty maven repo on my system. Can you provide more info so I can reproduce the reported error?

**Comment by wvdhaute** [comment]
I have the same build issue on another machine, investigating

**Comment by jcocoder** [comment]
thanks !
