### ISSUE TITLE
Using default credential provider chain

### ISSUE THREAD

**Issue by aleksandersumowski** [link-nv/logback-s3-rolling-policy#15]
awsAccessKey and awsSecretKey are documented as mandatory. It feels like a bad practice from security perspective.

Is there any specific reason why it wouldn't work with AWS SDK default credential provider chain?

**Comment by dhouthoo** [comment]
This might be a documentation issue. Looking at the code it seems that if you don't provide those variables it falls back to the default chain.

**Comment by aleksandersumowski** [comment]
Documentation issue is still an issue ...
