### ISSUE TITLE
Does this work in combination with SiftAppender

### ISSUE THREAD

**Issue by vish91** [link-nv/logback-s3-rolling-policy#16]
Hi guys, I see logback provides different types of Appenders as configuration in logback.xml. So, just asking before I give it a try:
Would you happen to know of I can do something like, using a Sift Appender for using dynamic discriminator for dynamic file creations and using S3FixedSized Rolling policy in combination for pushing those dynamic files out to S3 ? 
Something like this, using the incoming request's sessionID to create log files per session using your rolling S3 appender to upload those to S3 bucket with sessionID as bucket keys.

**Comment by dhouthoo** [comment]
We haven't tried that combination. Good luck and feel free the add the outcome of your experiments to this thread.

**Comment by vish91** [comment]
@dhouthoo thanks for response. I'll try and let you know in couple days. 
Meanwhile, there seems to be a problem with the index that it's using on `S3FixedWindowRollingPolicy.`
Files uploaded to S3 for this appender are the same name (the files themselves are unique and also has timestamp prefix), the index `%i` does not seem to be iterate over while uploading files to S3. 

```
<appender name="AUDIT-FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>logs/mylog.csv</file>
        <encoder>
            <pattern>%d{"yyyy-MM-dd HH:mm:ss.SSSSSSSSS"},%msg%n</pattern>
        </encoder>
        <rollingPolicy class="ch.qos.logback.core.rolling.S3FixedWindowRollingPolicy">
            <fileNamePattern>logs/mylog.%i.csv.gz</fileNamePattern>
            <s3BucketName>test</s3BucketName>
            <s3FolderName>test-logs/year=%d{yyyy}/month=%d{MM}/day=%d{dd}</s3FolderName>
            <rolloverOnExit>true</rolloverOnExit>
            <shutdownHookType>JVM_SHUTDOWN_HOOK</shutdownHookType>
            <prefixTimestamp>true</prefixTimestamp>
            <prefixIdentifier>true</prefixIdentifier>
        </rollingPolicy>
        <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
            <maxFileSize>100KB</maxFileSize>
        </triggeringPolicy>
    </appender>
```

![screen shot 2019-02-20 at 12 14 38 pm](https://user-images.githubusercontent.com/3489396/53118075-90b0e280-3509-11e9-80e7-79c7a06b9a5f.png)

Let me know if you are able to reproduce this or have encountered this before. 
Thanks

**Comment by vish91** [comment]
@dhouthoo 
Think I found the problem with file names.
https://github.com/link-nv/logback-s3-rolling-policy/blob/master/src/main/java/ch/qos/logback/core/rolling/S3FixedWindowRollingPolicy.java#L73
rollover() is always calling uploadFileToS3Async with getMinIndex() which will always be `1`.
