### ISSUE TITLE
please update aws-sdk version

### ISSUE THREAD

**Issue by moc-yuto** [link-nv/logback-s3-rolling-policy#3]
Hello, My project uses aws-sdk-java by this library and another library.
The other library needs to use aws-sdk-java version 1.10.
so I want it to be updated aws-sdk-java version.
https://github.com/link-nv/logback-s3-rolling-policy/blob/master/pom.xml#L65

**Comment by giannivh** [comment]
Updated the AWS SDK to the newest version (1.11.7), released as 1.4

**Comment by moc-yuto** [comment]
thx!!
