### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by achenchik** [link-nv/logback-s3-rolling-policy#4]
Hello guys,

Could you please clarify your license policy regarding usage of logback-s3-rolling-policy in other projects. 
As I see you've attached Apache 2 license to GitHub project: https://github.com/link-nv/logback-s3-rolling-policy/blob/master/LICENSE.txt

But here 

https://github.com/link-nv/logback-s3-rolling-policy/blob/master/src/main/java/ch/qos/logback/core/rolling/data/CustomData.java 

you have another license information

```
/*
 * SafeOnline project.
 *
 * Copyright 2006-2013 Lin.k N.V. All rights reserved.
 * Lin.k N.V. proprietary/confidential. Use is subject to license terms.
 */
```

So the question - can we use it in our (closed source) project?

Thanks in advance

**Comment by giannivh** [comment]
Hi,

Sorry about the confusion, I've updated the license. Please update to 1.5.
