### ISSUE TITLE
Repository is down

### ISSUE THREAD

**Issue by moc-yuto** [link-nv/logback-s3-rolling-policy#5]
`http://repo.linkid.be/releases` is down..
Could you up your server or create another repo.

Thanks.

**Comment by moc-yuto** [comment]
Now, I cannot access the repo because of 403Forbidden.
Please be public it.

**Comment by piotr-kukla** [comment]
I have the same problem :(

**Comment by wvdhaute** [comment]
Hello,

This was due to a move of our form maven repository to a new location.
I have deployed version 1.5 and a new 1.6 to test our release process.

Kind regards,
Wim.

**Comment by piotr-kukla** [comment]
Hm...
http://repo.linkid.be/releases is still forbidden :(
What can we do ?

**Comment by wvdhaute** [comment]
Hello,

Our maven repository is no longer browsable, but the artifacts are there and public.

See for example: repo.linkid.be/home/maven/repository/releases/ch/qos/logback/logback-s3-rolling-policy/1.5/logback-s3-rolling-policy-1.5.jar

Kind regards,
Wim.

**Comment by piotr-kukla** [comment]
Thanks.
You still have to update your wiki (#Usage section):
{code}
<url>http://repo.linkid.be/home/maven/repository/releases</url>
{code}

**Comment by wvdhaute** [comment]
Hey,

The artifacts were deployed to a wrong location on our new repo, I did not notice it right away.
I have fixed this so you can change it back to http://repo.linkid.be/releases as it was before.

Apologies for this,
Kind regards,
Wim.

**Comment by moc-yuto** [comment]
Thanks.
